x=("apple","papaya","blueberry","blackberry","banana")
print(x)
print(type(x))
print(len(x))
print(x[1])
print(x)
print(x[4:])
print(x[1:3])
print(x[-4:-1])
print(x[:-4])
print(x[-1:])
print("papaya" in x)
print(x)
print("papaya" not in (x))
y=list(x)
print(y)
y.append("red")
print(y)
y.remove("red")
print(y)
x=tuple(y)
print(x)
for i  in x:
    print(i)
a=("potato","tomato","pen")
print(x+a)    
print(x*3)
print(x.count("papaya"))


