x=("apple","watermelon","papaya")
print(x)
print(type(x))
print(len(x))
print(x[2])
print(x[1:3])
print(x[2:])
print(x[-3:-1])
print("watermelon" in x)
print("watermelon" not in x)
y=list(x)
print(y)
y.append("door")
print(y)
y.remove("apple")
print(y)
x=tuple(y)
print(x)
for i in x:
    print(i)
a=("blue","red","yellow")
print(x+a)
print(x*4)
print(x.count("door"))